### ISSUE TITLE
Date picker randomly crashing on iOS

### ISSUE THREAD

**Issue by REBELinBLUE** [danielhanold/danielhanold.pickerwidget#8]
If I use the date picker, including the example code randomly when activating it on iOS I get the following

      [ERROR] Script Error {
      [ERROR]     backtrace = "#0 Controller() at file:///Users/stephen/Library/Developer/CoreSimulator/Devices/C248FB08-0174-49E1-9DFF-4292F6CF857C/data/Containers/Bundle/Application/DA3E6DB4-6F4F-40BD-97A2-C307F8CE5C52/La%20Tasca.app/alloy/widgets/danielhanold.pickerWidget/controllers/widget.js:236\n#1 () at file:///Users/stephen/Library/Developer/CoreSimulator/Devices/C248FB08-0174-49E1-9DFF-4292F6CF857C/data/Containers/Bundle/Application/DA3E6DB4-6F4F-40BD-97A2-C307F8CE5C52/La%20Tasca.app/alloy.js:260\n#2 () at file:///Users/stephen/Library/Developer/CoreSimulator/Devices/C248FB08-0174-49E1-9DFF-4292F6CF857C/data/Containers/Bundle/Application/DA3E6DB4-6F4F-40BD-97A2-C307F8CE5C52/La%20Tasca.app/alloy/controllers/register.js:328";
      [ERROR]     line = 78;
      [ERROR]     message = "-[UIPickerView setDatePickerMode:]: unrecognized selector sent to instance 0x797ceba0";
      [ERROR]     sourceId = 325739168;
      [ERROR]     sourceURL = "file:///Users/stephen/Library/Developer/CoreSimulator/Devices/C248FB08-0174-49E1-9DFF-4292F6CF857C/data/Containers/Bundle/Application/DA3E6DB4-6F4F-40BD-97A2-C307F8CE5C52/La%20Tasca.app/alloy/widgets/danielhanold.pickerWidget/controllers/widget.js";
      [ERROR] }

Which appears to be this line

      picker.setType(Ti.UI.PICKER_TYPE_DATE);

However, I have noticed that if I change line 7 of pickerView.js from

      if (args.type === 'date-picker' && OS_ANDROID)

to 

      if (args.type === 'date-picker')

It works fine.

This has been happening on both iOS 8 and 8.1

I have uploaded a video showing this behaviour https://dl.dropboxusercontent.com/u/239816/Untitled.m4v

It is just a view with a label with an onClick button

https://gist.github.com/REBELinBLUE/2d4cf750bd01b78e1d1c

**Comment by danielhanold** [comment]
Sorry for this _very_ late reply.

I've been experiencing intermittent issues as well and adjusted the widget to reflect your changes. See https://github.com/danielhanold/danielhanold.pickerwidget/commit/05b9e3423bc2183e8bae24bbec84bad16e2ccfd8
